Hibajavítások
reformatus/enekeskonyv-app pull request #23
Opened 2023-01-02 17:18 UTC by RedyAu

2023-01-03 10:18 UTC, boobaa requested changes

2023-01-03 10:18 UTC, boobaa commented on lib/song_page.dart
> +                                    scrollController.animateTo(0,
jumpTo: énekváltáskor nem akarjuk a lapozás miatti csúsztatás effektet, ugorjon csak egyből az oldal tetejére.

2023-01-03 10:18 UTC, boobaa commented on lib/song_page.dart
> +                                    scrollController.animateTo(0,
jumpTo: énekváltáskor nem akarjuk a lapozás miatti csúsztatás effektet, ugorjon csak egyből az oldal tetejére.

2023-01-03 12:54 UTC, boobaa commented on ios/Runner/Info.plist
> +	<string>Énekeskönyv</string>
Nem fér bele az egész? vagy ez jelenik meg valahol?

2023-01-03 12:54 UTC, boobaa commented on ios/Flutter/AppFrameworkInfo.plist
> +  <string>11.0</string>
Mi miatt muszáj kihajítani a régebbi, még mindig használható telefonok támogatását?

2023-01-03 12:57 UTC, boobaa commented on ios/Runner/Info.plist
> +	<string>Énekeskönyv</string>
Ha meg beleférne, akkor pls legyen konzisztens: előre a 21, s csak utána a 48 (hiszen a 21 már a default).

2023-01-03 13:16 UTC, RedyAu commented on ios/Flutter/AppFrameworkInfo.plist
> +  <string>11.0</string>
Flutter csak iOS 11-től támogatott.

2023-01-04 10:28 UTC, boobaa approved these changes

2023-01-04 10:31 UTC, merged